language: java
cache:
  directories:
    - "$HOME/.gradle"
    - "$HOME/.m2/repository"
jdk:
  - oraclejdk8
script:
#  - mvn clean test package
  - gradle --version
  - gradle clean test jar

#after_success:
#  - gradle jacocoTestReport coveralls
